### ISSUE TITLE
Channel pool support in ChannelFactory

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-rabbitmq#9]
Need a pooling ChannelFactory to optimize publishers (see #4) 

## Background

Named Connections are already cached inside the Bootique `ConnectionManager` (one per symbolic name). [Channels](https://www.rabbitmq.com/channels.html) are single-threaded abstractions that work on top of connections, and looks like they are worth pooling.

E.g. `RmqPublisher` opens and closes a Channel for each publish operation, which simplifies the calling code, but creates noticeable overhead. It does look like a pooling ChannelFactory would help here.

For _consumers_, the docs seem to [suggest using one channel per Consumer](https://www.rabbitmq.com/api-guide.html#consuming). So pooling is probably not required.

## Implementation 
Caching channels is done per connection and is decoupled from creating topologies (see #17). To enable channel caching, set `channelPoolCapacity` to a value above zero:
```yaml
rabbitmq:
  channelPoolCapacity: 4
```

## Reference links: 
* Project Reactor has a [RabbitMQ channel pool](https://projectreactor.io/docs/rabbitmq/milestone/reference/#_channel_pooling_in_code_sender_code). 
* [Advise](https://www.cloudamqp.com/blog/2018-01-19-part4-rabbitmq-13-common-errors.html) on Channel and Connection reuse (single send and single receive connection)
* Potentially conflicting [advise](https://www.rabbitmq.com/channels.html#resource-usage) from RMQ docs (limit the # of channels to single digits per connection)

**Comment by andrus** [comment]
Also observing delivery failures under load that may potentially be due to the quick channels churn, and may be fixed via channel pooling. The exception is on close within RmqMessageBuilder, but it hides the fact that the the message is not actually delivered. 
```
Caused by: java.util.concurrent.TimeoutException: null
 at com.rabbitmq.utility.BlockingCell.get(BlockingCell.java:77)
 at com.rabbitmq.utility.BlockingCell.uninterruptibleGet(BlockingCell.java:120)
 at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
 at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:502)
 at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:617)
 at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:542)\r\n at com.rabbitmq.client.impl.ChannelN.close(ChannelN.java:535)
 at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.lambda$close$0(AutorecoveringChannel.java:74)
 at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.executeAndClean(AutorecoveringChannel.java:102)
 at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.close(AutorecoveringChannel.java:74)
 at io.bootique.rabbitmq.client.pubsub.RmqMessageBuilder.publish(RmqMessageBuilder.java:93)
```

**Comment by andrus** [comment]
Looks like the Channel pool will need to be attached to the `RmqPubEndpoint` and can only be used for the default "publish" method that uses a predefined topology. 

I suppose we DO NOT need to close `RmqPubEndpoint` via ShutdownManager to cleanup up cached Channels, as it should be enough to close the underlying connections? Still a close method is in order there for manual endpoint management.

**Comment by andrus** [comment]
This solution caches channels, but doesn't do anything special for topology
